# Copyright 2026 The MathWorks, Inc.
description: Audio Toolbox, DSP HDL Toolbox, DSP System Toolbox, Signal Processing Toolbox, and Wavelet Toolbox.
keywords:
  - matlab
  - signal-processing
  - dsp
  - audio
  - filtering
