# Copyright 2026 The MathWorks, Inc.
display-name: "Signal Processing"
description: MATLAB, Simulink, Audio Toolbox, DSP HDL Toolbox, DSP System Toolbox, Fixed-Point Designer, HDL Coder, Signal Processing Toolbox, and Wavelet Toolbox.
keywords:
  - matlab
  - signal-processing
  - dsp
  - audio
  - filtering
