# Copyright 2026 The MathWorks, Inc.
display-name: "Wireless Communications"
description: MATLAB, 5G Toolbox, Bluetooth Toolbox, Communications Toolbox, Satellite Communications Toolbox, Wireless Network Toolbox, Wireless Testbench, WLAN Toolbox, and Wireless Testbench Support Package for NI USRP Radios.
keywords:
  - matlab
  - wireless
  - communications
  - 5g
  - lte
  - wlan
  - wifi
  - 802.11
  - satellite
  - gnss
  - gps
  - galileo
  - navic
  - dvb-s2
  - dvb-s2x
  - dvb-rcs2
  - ccsds
  - superframes
  - tm-tc
  - sda
  - Bluetooth
  - Ble

