# Copyright 2026 The MathWorks, Inc.
display-name: "Code Generation"
description: MATLAB, Embedded Coder, Fixed-Point Designer, GPU Coder, MATLAB Coder, MATLAB Test, Parallel Computing Toolbox, and MATLAB Coder Support Package for PyTorch and LiteRT Models.
keywords:
  - matlab
  - code-generation
  - fixed-point
  - embedded-coder
  - gpu-coder
  - matlab-coder
  - ai-model
  - pytorch-code-generation
