# Copyright 2026 The MathWorks, Inc.
description: Image Processing Toolbox, Computer Vision Toolbox, Lidar Toolbox, and Medical Imaging Toolbox.
keywords:
  - matlab
  - image-processing
  - computer-vision
  - lidar
  - medical-imaging
