# Copyright 2026 The MathWorks, Inc.
display-name: "Parallel Computing"
description: MATLAB, Parallel Computing Toolbox, and MATLAB Parallel Server.
keywords:
  - matlab
  - parallel-computing
  - parfor
  - gpu
