function manifest = tbxManifest()
%TBXMANIFEST Dependency manifest for the toolbox.

    manifest.generated = "2026-05-11";
    manifest.toolbox_root = pwd;

    % Files shipping in the .mltbx
    manifest.included = { ...
        "+pkg/functionA.m"; ...
        "+pkg/functionB.m"; ...
    };

    % MathWorks product requirements
    manifest.products = { ...
        struct("name", "Statistics and Machine Learning Toolbox", ...
               "used_by", {{"+pkg/functionB.m"}}, ...
               "functions", {{"fitlm", "predict"}}); ...
    };

    % Add-on dependencies
    manifest.addons = { ...
        struct("name", "SharedUtils", "version", "1.2.0", ...
               "used_by", {{"+pkg/functionC.m"}}); ...
    };

    % Resolved externals (user-approved actions taken)
    manifest.resolved = { ...
        struct("file", "helperB.m", "action", "copied_in", ...
               "original_path", "C:\shared\helperB.m"); ...
    };

    % Unresolved (user deferred or pipeline blocked pending separate packaging)
    manifest.unresolved = { ...
        struct("files", {{"shared/logging.m", "shared/formatMsg.m"}}, ...
               "action", "pending_outward_refactor", ...
               "notes", "User chose to package as separate add-on"); ...
    };

    % Ignore file conflicts
    manifest.ignore_conflicts = {};
end

% Copyright 2026 The MathWorks, Inc.
