# Copyright 2026 The MathWorks, Inc.
display-name: "Computational Finance"
description: MATLAB, Datafeed Toolbox and Spreadsheet Link.
keywords:
  - matlab
  - finance
  - datafeed
  - spreadsheet-link
  - excel
