# Copyright 2026 The MathWorks, Inc.
display-name: "Automotive"
description: MATLAB, Simulink, Automated Driving Toolbox, Computer Vision Toolbox, RoadRunner, RoadRunner Scenario, RoadRunner Scene Builder, Sensor Fusion and Tracking Toolbox, Automated Driving Toolbox Interface for Eclipse SUMO Traffic Simulator, and Scenario Builder for Automated Driving Toolbox.
keywords:
  - matlab
  - automotive
  - automated-driving
  - roadrunner
  - roadrunner-scene-builder
  - rrhd
  - hd-map
  - lanelet2
  - scene-import
  - asset-mapping
  - vehicle-dynamics
